#!/usr/bin/env python3
"""Build the canonical MT/TR SQLite database and a derived Obsidian vault.

KJV is deliberately excluded from SQLite. KJV + Strong's belongs in a separate
Obsidian-only adapter.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import sqlite3
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "build"
DB = BUILD / "bible_mt_tr.sqlite"
VAULT = BUILD / "obsidian-vault"
SCHEMA = ROOT / "config" / "schema.sql"
SOURCES = ROOT / "config" / "sources.toml"

BOOKS = [
("Gen","Genesis"),("Exo","Exodus"),("Lev","Leviticus"),("Num","Numbers"),("Deu","Deuteronomy"),
("Jos","Joshua"),("Jdg","Judges"),("Rut","Ruth"),("1Sa","1 Samuel"),("2Sa","2 Samuel"),
("1Ki","1 Kings"),("2Ki","2 Kings"),("1Ch","1 Chronicles"),("2Ch","2 Chronicles"),
("Ezr","Ezra"),("Neh","Nehemiah"),("Est","Esther"),("Job","Job"),("Psa","Psalms"),
("Pro","Proverbs"),("Ecc","Ecclesiastes"),("Sng","Song of Solomon"),("Isa","Isaiah"),
("Jer","Jeremiah"),("Lam","Lamentations"),("Ezk","Ezekiel"),("Dan","Daniel"),
("Hos","Hosea"),("Jol","Joel"),("Amo","Amos"),("Oba","Obadiah"),("Jon","Jonah"),
("Mic","Micah"),("Nam","Nahum"),("Hab","Habakkuk"),("Zep","Zephaniah"),("Hag","Haggai"),
("Zec","Zechariah"),("Mal","Malachi"),("Mat","Matthew"),("Mrk","Mark"),("Luk","Luke"),
("Jhn","John"),("Act","Acts"),("Rom","Romans"),("1Co","1 Corinthians"),
("2Co","2 Corinthians"),("Gal","Galatians"),("Eph","Ephesians"),("Php","Philippians"),
("Col","Colossians"),("1Th","1 Thessalonians"),("2Th","2 Thessalonians"),
("1Ti","1 Timothy"),("2Ti","2 Timothy"),("Tit","Titus"),("Phm","Philemon"),
("Heb","Hebrews"),("Jas","James"),("1Pe","1 Peter"),("2Pe","2 Peter"),
("1Jn","1 John"),("2Jn","2 John"),("3Jn","3 John"),("Jud","Jude"),("Rev","Revelation")
]

def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()

def safe_write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")

def create_db() -> sqlite3.Connection:
    BUILD.mkdir(parents=True, exist_ok=True)
    if DB.exists():
        DB.unlink()

    con = sqlite3.connect(DB)
    con.executescript(SCHEMA.read_text(encoding="utf-8"))

    for i, (osis, name) in enumerate(BOOKS, 1):
        testament = "OT" if i <= 39 else "NT"
        con.execute(
            "INSERT INTO books(id,testament,osis,name,sort_order) VALUES(?,?,?,?,?)",
            (i, testament, osis, name, i),
        )

    config = tomllib.loads(SOURCES.read_text(encoding="utf-8"))
    source_rows = [
        ("STEPBible", config.get("stepbible", {}).get("base", ""), None, None,
         "Public source base; exact adapters should pin individual files."),
        ("Open Scriptures HebrewLexicon",
         config.get("openscriptures", {}).get("hebrew_lexicon", ""), None, None,
         "Hebrew lexical reference."),
        ("Open Scriptures morphHB",
         config.get("openscriptures", {}).get("morphhb", ""), None, None,
         "Hebrew morphology reference."),
    ]

    for name, url, license_name, digest, notes in source_rows:
        con.execute(
            """INSERT OR IGNORE INTO sources
               (name,url,license,sha256,notes)
               VALUES(?,?,?,?,?)""",
            (name, url, license_name, digest, notes),
        )

    con.commit()
    return con

def write_source_manifest(con: sqlite3.Connection) -> None:
    rows = con.execute("""
        SELECT name,url,license,sha256,downloaded_at,notes
        FROM sources ORDER BY name
    """).fetchall()

    fields = ["name","url","license","sha256","downloaded_at","notes"]
    payload = [dict(zip(fields, row)) for row in rows]
    safe_write(
        BUILD / "source_manifest.json",
        json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
    )

def generate_obsidian(con: sqlite3.Connection) -> None:
    if VAULT.exists():
        shutil.rmtree(VAULT)

    safe_write(
        VAULT / "_meta" / "README.md",
        """# Bible MT/TR Research Vault

Generated from `bible_mt_tr.sqlite`.

- MT/WLC and TR are the controlling textual layers.
- KJV is reference-only and is not stored in SQLite.
- KJV + Strong's is generated by a separate Obsidian adapter.
""",
    )

    # The current bootstrap has the schema/books but no verse records until the
    # source-specific MT/TR adapters are enabled.
    for _, name in BOOKS:
        safe_write(
            VAULT / "Books" / f"{name}.md",
            f"""---
type: book
source_layer: MT/TR
---

# {name}
""",
        )

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--fresh", action="store_true")
    parser.parse_args()

    con = create_db()
    generate_obsidian(con)

    report = {
        "books": con.execute("SELECT COUNT(*) FROM books").fetchone()[0],
        "verses": con.execute("SELECT COUNT(*) FROM verses").fetchone()[0],
        "words": con.execute("SELECT COUNT(*) FROM words").fetchone()[0],
        "lemmas": con.execute("SELECT COUNT(*) FROM lemmas").fetchone()[0],
        "strongs": con.execute("SELECT COUNT(*) FROM strongs").fetchone()[0],
        "morphology": con.execute("SELECT COUNT(*) FROM morphology").fetchone()[0],
        "lexicon_entries": con.execute(
            "SELECT COUNT(*) FROM lexicon_entries"
        ).fetchone()[0],
        "kjv_in_sqlite": False,
    }
    con.close()

    safe_write(
        BUILD / "build_report.json",
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
    )
    write_source_manifest(sqlite3.connect(DB))

    hashes = []
    for path in (
        DB,
        BUILD / "build_report.json",
        BUILD / "source_manifest.json",
    ):
        hashes.append(f"{sha256(path)}  {path.name}")
    safe_write(BUILD / "SHA256SUMS", "\n".join(hashes) + "\n")

    print(json.dumps(report, ensure_ascii=False, indent=2))

if __name__ == "__main__":
    main()
